Вывести четные числа по возрастанию в заданном количестве.
InTeam7/-Homework pull request #14
Opened 2024-06-14 22:01 UTC by danqa03

2024-06-15 07:28 UTC, InTeam7 requested changes

2024-06-15 07:28 UTC, InTeam7 commented on Homework/Homework/Program.cs
> +            evenNumbers[i] = (i+1) *2;
```suggestion
        for (int i = 1; i <= count; i++)
        {
            evenNumbers[i-1] = i * 2;
```

мб так удобнее?

2024-06-15 07:28 UTC, InTeam7 commented on Homework/Homework/Program.cs
> +        for (int i = 0; i < count; i++)
```suggestion
        for (int i = 0; i < evenNumbers.Length; i++)
```
И еще лучше всегда делать так

2024-06-15 07:29 UTC, InTeam7 commented
А че смайлик типа так себе, интересная задачка вообще то

2024-06-15 12:49 UTC, danqa03 commented
Задачка то топ, времени потратил миллиард, а решение было под носом. Не с тем работал короче

2024-06-15 22:30 UTC, danqa03 commented on Homework/Homework/Program.cs
> +            evenNumbers[i] = (i+1) *2;
Чем же? По моему больше мусора добавил чисто🤣

2024-06-16 07:08 UTC, InTeam7 commented on Homework/Homework/Program.cs
> +            evenNumbers[i] = (i+1) *2;
(i+1) *2 вот это выражение выглядит как то не комильфо ну да ладно, и так и так сойдет

2024-06-17 13:34 UTC, merged